feat: separate commands for solo node delete
hashgraph/solo pull request #597
Opened 2024-09-18 11:18 UTC by Ivo-Yankov

## Description

This pull request changes the following:

* TBD

### Related Issues

* Closes #

2024-09-30 13:18 UTC, jeromy-cannon requested changes
see comments

2024-09-30 17:09 UTC, JeffreyDallas commented on .github/workflows/zxc-code-analysis.yaml
> +          name: ${{ inputs.e2e-relay-coverage-report }}
This step was accidentally deleted, need to revert

2024-09-30 19:20 UTC, JeffreyDallas commented on src/commands/node.mjs
> +              nodeCmd.logger.debug('==== Running \'node add\' ===')
should be Running \'node delete-prepare\'

2024-09-30 19:20 UTC, JeffreyDallas commented on src/commands/node.mjs
> +              nodeCmd.logger.debug('==== Running \'node add\' ===')
should be Running \'node delete-submit-transactions\'

2024-09-30 19:20 UTC, JeffreyDallas commented on src/commands/node.mjs
> +              nodeCmd.logger.debug('==== Running \'node add\' ===')
should be Running 'node delete-execute'

2024-09-30 20:18 UTC, JeffreyDallas commented on .github/workflows/flow-pull-request-checks.yaml
> -
Fixed

2024-09-30 20:18 UTC, JeffreyDallas commented on .github/workflows/zxc-code-analysis.yaml
> +          name: ${{ inputs.e2e-relay-coverage-report }}
Fixed

2024-10-01 11:59 UTC, jeromy-cannon approved these changes

2024-10-01 11:59 UTC, merged

2024-10-04 16:32 UTC, swirlds-automation commented
:tada: This PR is included in version 0.31.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@hashgraph/solo/v/0.31.0)
- [GitHub release](https://github.com/hashgraph/solo/releases/tag/v0.31.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: