chore: update readme with port forward example
hashgraph/solo pull request #620
Opened 2024-09-19 17:36 UTC by JeffreyDallas

## Description

This pull request changes the following:

* update readme with port forward example

### Related Issues

* Closes #516

2024-09-19 17:37 UTC, JeffreyDallas commented
Maybe we could proved a simple  `local_solo_launch.sh`

```
#!/usr/bin/env bash

./test/e2e/setup-e2e.sh

solo node keys --gossip-keys --tls-keys -i node1,node2,node3
solo network deploy -i node1,node2,node3
solo node setup -i node1,node2,node3
solo node start -i node1,node2,node3
solo mirror-node deploy
solo relay deploy -i node1

kubectl port-forward svc/relay-node1-hedera-json-rpc-relay -n solo-e2e 7546:7546 &
kubectl port-forward svc/haproxy-node1-svc -n solo-e2e 50211:50211 &
kubectl port-forward svc/fullstack-deployment-hedera-explorer -n solo-e2e 8080:80 &

```

2024-09-19 19:04 UTC, jeromy-cannon commented on README.md.template
> +  kubectl port-forward svc/haproxy-node1-svc -n "${SOLO_NAMESPACE}" 50211:50211 &
```suggestion
  kubectl port-forward svc/haproxy-node1-svc -n "${SOLO_NAMESPACE}" 50211:50211 &
  kubectl port-forward svc/haproxy-node2-svc -n "${SOLO_NAMESPACE}" 51211:50211 &
  kubectl port-forward svc/haproxy-node3-svc -n "${SOLO_NAMESPACE}" 52211:50211 &
```

2024-09-19 19:04 UTC, jeromy-cannon commented on README.md.template
> +  # enable portforwarding for haproxy
```suggestion
  # enable portforwarding for envoy proxy
```

2024-09-19 19:05 UTC, jeromy-cannon commented on README.md.template
> +  kubectl port-forward svc/envoy-proxy-node1-svc -n "${SOLO_NAMESPACE}" 8081:8080 &
```suggestion
  kubectl port-forward svc/envoy-proxy-node1-svc -n "${SOLO_NAMESPACE}" 8081:8080 &
  kubectl port-forward svc/envoy-proxy-node2-svc -n "${SOLO_NAMESPACE}" 8181:8080 &
  kubectl port-forward svc/envoy-proxy-node3-svc -n "${SOLO_NAMESPACE}" 8281:8080 &
```

2024-09-19 19:07 UTC, tomzhenghedera approved these changes

2024-09-19 19:31 UTC, jeromy-cannon requested changes
please make the updates I requested

2024-09-19 19:41 UTC, jeromy-cannon approved these changes

2024-09-19 20:25 UTC, merged

2024-10-04 16:33 UTC, swirlds-automation commented
:tada: This PR is included in version 0.31.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@hashgraph/solo/v/0.31.0)
- [GitHub release](https://github.com/hashgraph/solo/releases/tag/v0.31.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: