refactor(aliases): rename node ID references to node alias for clarity
hashgraph/solo pull request #625
Opened 2024-09-25 10:54 UTC by instamenta

## Description

1. Created new aliases for:
  * pod name
  *  node alias 
  *  node id

2.  Renamed const values of the flags for internal use to reflect their actual usage and value:
  * nodeIDs --> nodeAliasesUnparsed 
  * nodeID --> nodeAlias

3. Renamed all references appropriately.

### Related Issues

* Closes # [527](https://github.com/hashgraph/solo/issues/527)

2024-09-30 16:57 UTC, JeffreyDallas submitted a review, later dismissed

2024-10-01 16:28 UTC, JeffreyDallas commented
I would appreicate we have a shorter branch name, since my computer screen is not wide enough :-)

2024-10-01 19:29 UTC, jeromy-cannon commented on src/core/templates.mjs
>    static nodeIdFromFullyQualifiedNetworkSvcName (svcName) {
```suggestion
  static nodeAliasFromFullyQualifiedNetworkSvcName (svcName) {
```

2024-10-01 19:31 UTC, jeromy-cannon commented on src/commands/flags.mjs
rename `debugNodeId` to `debugNodeAlias`

2024-10-01 19:33 UTC, jeromy-cannon commented on src/commands/prompts.mjs
rename `promptNodeIds` to `promptNodeAliases`

2024-10-01 19:34 UTC, jeromy-cannon commented on src/commands/prompts.mjs
>  export async function promptNewNodeId (task, input) {
```suggestion
export async function promptNewNodeAlias (task, input) {
```

2024-10-01 19:35 UTC, jeromy-cannon commented on src/commands/node.mjs
> +        .setStakedNodeId(Templates.nodeNumberFromNodeAlias(nodeAlias) - 1)
```suggestion
        .setStakedNodeId(Templates.nodeIdFromNodeAlias(nodeAlias) - 1)
```

2024-10-01 19:40 UTC, jeromy-cannon commented on src/commands/node.mjs
from:
```
          const lastNodeNumberMatch = lastNodeName.match(/\d+$/)
          if (lastNodeNumberMatch.length) {
            const incremented = parseInt(lastNodeNumberMatch[0]) + 1
            lastNodeName = lastNodeName.replace(/\d+$/, incremented.toString())
          }
```
```
          const lastNodeIdMatch = lastNodeAlias.match(/\d+$/)
          if (lastNodeIdMatch.length) {
            const incremented = parseInt(lastNodeIdMatch[0]) + 1
            lastNodeAlias = lastNodeAlias.replace(/\d+$/, incremented.toString())
          }
```

2024-10-01 19:41 UTC, jeromy-cannon commented on src/commands/node.mjs
>                const savedStatePath = `${constants.HEDERA_HAPI_PATH}/data/saved/com.hedera.services.ServicesMain/${nodeNumber}/123/${savedStateDir}`
```suggestion
              const savedStatePath = `${constants.HEDERA_HAPI_PATH}/data/saved/com.hedera.services.ServicesMain/${nodeId}/123/${savedStateDir}`
```

2024-10-01 19:43 UTC, jeromy-cannon commented on src/commands/node.mjs
> +              const nodeNumber = Templates.nodeNumberFromNodeAlias(config.nodeAlias)
```suggestion
              const nodeId = Templates.nodeIdFromNodeAlias(config.nodeAlias)
```

2024-10-01 19:45 UTC, jeromy-cannon commented on test/test_util.js
from:
```
export async function getNodeIdsPrivateKeysHash (networkNodeServicesMap, namespace, k8, destDir) {
```
to
```
export async function getNodeAliasPrivateKeysHash (networkNodeServicesMap, namespace, k8, destDir) {
```

2024-10-01 19:46 UTC, jeromy-cannon commented on test/test_util.js
and update references inside of this method.

2024-10-01 19:48 UTC, jeromy-cannon requested changes
update `network_node_services.mjs`.`nodeName` to `nodeAlias`

2024-10-01 19:49 UTC, jeromy-cannon commented
Update references of `nodeName` to `nodeAlias`

2024-10-01 20:22 UTC, JeffreyDallas commented on test/test_util.js
Done

2024-10-01 20:22 UTC, JeffreyDallas commented on src/commands/node.mjs
>                const savedStatePath = `${constants.HEDERA_HAPI_PATH}/data/saved/com.hedera.services.ServicesMain/${nodeNumber}/123/${savedStateDir}`
Done

2024-10-01 20:22 UTC, JeffreyDallas commented on src/commands/node.mjs
Updated

2024-10-01 20:22 UTC, JeffreyDallas commented on src/commands/node.mjs
> +        .setStakedNodeId(Templates.nodeNumberFromNodeAlias(nodeAlias) - 1)
Updated

2024-10-01 20:22 UTC, JeffreyDallas commented on src/commands/prompts.mjs
>  export async function promptNewNodeId (task, input) {
Updated

2024-10-01 20:22 UTC, JeffreyDallas commented on src/commands/prompts.mjs
Updated

2024-10-01 20:22 UTC, JeffreyDallas commented on src/commands/flags.mjs
Updated

2024-10-01 20:22 UTC, JeffreyDallas commented on src/core/templates.mjs
>    static nodeIdFromFullyQualifiedNetworkSvcName (svcName) {
Updated

2024-10-02 14:36 UTC, jeromy-cannon approved these changes

2024-10-02 14:36 UTC, merged

2024-10-04 16:32 UTC, swirlds-automation commented
:tada: This PR is included in version 0.31.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@hashgraph/solo/v/0.31.0)
- [GitHub release](https://github.com/hashgraph/solo/releases/tag/v0.31.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: