feat: update readme and hugo workflow
hashgraph/solo pull request #930
Opened 2024-12-05 18:15 UTC by JeffreyDallas

## Description

This PR is part of resolving issue 914
* Split the original long README.md into many sections markdown documents
* Manually verified that all testing steps, fixed some old / incorrect instrctions
* Added new sections for CLI (may need further split)
* Updated hugo main page to support the new strcuture.

----

![image](https://github.com/user-attachments/assets/20b480d7-97d5-4e51-a984-e0e0f21632c6)

2024-12-06 14:11 UTC, jeromy-cannon requested changes
looks like we are getting autocommits in our PRs. Can we stop doing this?  Also, your check code style is failing

2024-12-09 07:46 UTC, mishomihov00 approved these changes
Review applies to 
`.github/workflows/flow-hugo-publish.yaml`
`.github/workflows/zxc-update-readme.yaml`
`docs/data/menu/main.yml`

2024-12-09 14:38 UTC, jeromy-cannon approved these changes

2024-12-09 14:38 UTC, merged

2024-12-31 21:28 UTC, swirlds-automation commented
:tada: This PR is included in version 0.32.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@hashgraph/solo/v/0.32.0)
- [GitHub release](https://github.com/hashgraph/solo/releases/tag/v0.32.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: